
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON NUMBER PLUS STAR STARARG VARexpression : expression PLUS termexpression : termterm : NUMBERterm : VARterm : STAR STARARGterm : factor COLON VARfactor : factor COLON VARfactor : VAR'
    
_lr_action_items = {'NUMBER':([0,7,],[3,3,]),'VAR':([0,7,9,],[4,4,11,]),'STAR':([0,7,],[5,5,]),'$end':([1,2,3,4,8,10,11,],[0,-2,-3,-4,-5,-1,-6,]),'PLUS':([1,2,3,4,8,10,11,],[7,-2,-3,-4,-5,-1,-6,]),'COLON':([4,6,11,],[-8,9,-7,]),'STARARG':([5,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'term':([0,7,],[2,10,]),'factor':([0,7,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','formula_parser.py',84),
  ('expression -> term','expression',1,'p_expression_term','formula_parser.py',89),
  ('term -> NUMBER','term',1,'p_term_number','formula_parser.py',93),
  ('term -> VAR','term',1,'p_term_var','formula_parser.py',97),
  ('term -> STAR STARARG','term',2,'p_term_star','formula_parser.py',101),
  ('term -> factor COLON VAR','term',3,'p_term_factor','formula_parser.py',106),
  ('factor -> factor COLON VAR','factor',3,'p_factor_facotr','formula_parser.py',110),
  ('factor -> VAR','factor',1,'p_factor_var','formula_parser.py',114),
]
